### ISSUE TITLE
APIのエンドポイント及びリクエストメソッドをRESTの原則に適合させる

### ISSUE THREAD

**Issue by potato4d** [tonkatsu-ansin/Glendar#2]
@AC3ROZ 
以下ご確認ください

現状エンドポイントがRESTの原則に則ってないので、こんな感じにしたらどうかな、という提案です。

### Before
[GET] /api/board/
[GET] /api/waiting/

### After
[GET] /boards/

* REST APIのエンドポイントは基本的に複数形であるべきなのでboardsとする。
* コンポーネントのhidden/visibleは受け取った人間が扱うべきなので、コンポーネントの一つ一つのオブジェクトに対して付与していく形のほうが良さそうなので、盤面データ全部返すように二者を統合

### Before
[UPDATE] /api/update

### After
[UPDATE] /api/components

* 対象+メソッドの形に置き換え

### Before
[POST] /api/add

### After
[POST] /api/components

* 対象+メソッドの形に書き換え

**Comment by AC3ROZ** [comment]
OK

**Comment by potato4d** [comment]
/api/boards/users/

**Comment by potato4d** [comment]
api/boards/1/users/

**Comment by AC3ROZ** [comment]
fixed 3f8c8c70e46504bbce9e3b80c037fef0e02b6e17
