### ISSUE TITLE
攻撃範囲の追加(どどんとふのログホライズン範囲)

### ISSUE THREAD

**Issue by potato4d** [tonkatsu-ansin/Glendar#32]

**Comment by potato4d** [comment]
取り敢えず、色は黒固定の半透明で範囲だけ変更可能なものでβ機能として出してしまいたいかなぁと思っている。
現在モーダルを実装中。

**Comment by potato4d** [comment]
コンポーネントとしての仕様としては、今後こういった範囲系が増えていくので、componentのtypeに'range'を追加して、各種範囲の可視化に当てるのが良いかなぁという印象。

type=="range"のものは、追加で判別用のフラグをもたせて、判別用フラグ内のパラメータに応じて、矩形選択, 菱形選択, 丸型選択を作れる作りにしたい

**Comment by potato4d** [comment]
無限に実装したくなくなってきた

**Comment by potato4d** [comment]
菱形実装案

1. 無限泥臭いdiv

xとyの数だけループしてdivを作って菱形を作る。
泥臭いだけあって愚直な方法だけど、可読性とかだるそうで、パフォーマンスと管理が大変そう。
実装は簡単で、菱形全体を掴みたい場合にも対応しやすい。

2. linear-gradientゴリ押し

ないと思う。クリック範囲が矩形になる

3. canvas

ゴリゴリ書くのはありかもしれない、ただ、ここだけcanvasってどうなのっていうのと、クリック範囲が矩形になる

**Comment by potato4d** [comment]
これの作り方はまた考えます

**Comment by potato4d** [comment]
canvas採用→ゴリ押し描画→canvasにpointer-eventsを載せない→position:absolute辺りで親要素の範囲を汚さない→クリックは中央だけだけど見た目は大きくなる

みたいな動きが一番良さそう

**Comment by himanoa** [comment]
一回泥草divで実装してみて様子見てもいい気がする

**Comment by potato4d** [comment]
今日気たら話そうぜ！

**Comment by himanoa** [comment]
O(k)

**Comment by otofune** [comment]
結局どうなったんだ

**Comment by potato4d** [comment]
Glendar開発やるぞって言ってたらひまのあが風邪引いててひまのあ風邪引いてるならタスク溜まってるし別の消化するか……ってなったので多分次に集まる時に全部決まる（？）

**Comment by potato4d** [comment]
https://github.com/tonkatsu-ansin/Glendar/tree/issues/%2332
