### ISSUE TITLE
チャットパレット実装

### ISSUE THREAD

**Issue by potato4d** [tonkatsu-ansin/Glendar#34]

**Comment by potato4d** [comment]
チャパレ、こういう感じで（これは別にデザインではないので方針が決定したらちゃんと作ろう）、チャットログの右とかにあるとサクッと使えて便利そうだけどどうという気持ち。

今後チャットのチャンネルを複数持つことを想定するなら、そっちのタブに格納するのもありだけど、今のGlendarの開発の構想的にはこれが正しい気がする

<img width="1440" alt="2017-01-07 4 54 31" src="https://cloud.githubusercontent.com/assets/6993514/21730954/746083c8-d495-11e6-9077-3655da31c4b1.png">

**Comment by potato4d** [comment]
@AC3ROZ

**Comment by potato4d** [comment]
あーでもこれ1366だとつらそう

**Comment by himanoa** [comment]
1366だとキツそうはあるよなぁ

**Comment by potato4d** [comment]
だよなぁ

**Comment by potato4d** [comment]
body here...をクリックしたら出てくるようにすれば良いのでは！？

**Comment by himanoa** [comment]
それが良さそう 👍

**Comment by potato4d** [comment]
OK、これでいくぜ

**Comment by himanoa** [comment]
チャットパレット、1つずつ追加するの割りとつらそうだしこの辺一括でドカッとコピペできる仕組みが会ってもいいかも（DSLみたいなの実装して変数とか使えるとかなり:+1:が強い）

**Comment by potato4d** [comment]
単純にチャパレの追加時に改行で区切って追加とか、もしくは編集自体を改行で区切ってパースストーンとかじゃないと非エンジニアフレンドリーじゃないかも。

しかしまぁ、どかっと追加できる仕組みはいると思うので、編集をモーダルに出してやっても良い

**Comment by himanoa** [comment]
表示領域に余裕があればどっちもできる感じにするのがベストな感じする

**Comment by potato4d** [comment]
せやな

**Comment by himanoa** [comment]
こういう感じが理想な気がする（プログラマライクすぎる気もするが） http://www.pixiv.net/novel/show.php?id=3970697#3

**Comment by potato4d** [comment]
これやるならもうアクションパレットみたいなの作ってアイコンクリックで振りたい(俺は)かなぁ

**Comment by himanoa** [comment]
ユーザー側で定義できる枠組みがあるのがでかいと思う

**Comment by potato4d** [comment]
TRPGするために言語覚えるのおかしい感じはなくはないみたいなとこ

**Comment by potato4d** [comment]
TRPGするために言語覚えるのおかしい感じはなくはないみたいなとこ

**Comment by potato4d** [comment]
馬鹿なので間違えてクローズした

**Comment by himanoa** [comment]
😄

**Comment by potato4d** [comment]
なるほどね

**Comment by himanoa** [comment]
言語っていうほど重くない感じのレベルのDSLがほしい気がする

**Comment by potato4d** [comment]
チャパレ、どっちかというと、ユーザーよりGMが重宝しそうな昨日だと思ってて、想定ユーザーそっちでいくならGMだけ覚えてもらうぐらいはありだけどPL全員に覚えてもらうのは厳しそう

**Comment by himanoa** [comment]
アンケ取ってく感じの気持ちが強い

**Comment by potato4d** [comment]
まぁそれでも良いがはじめからここにこだわらんでもええよなという感じだしまずただのテンプレで作ってからキメような

**Comment by potato4d** [comment]
done
